Controllers/HemnetController.cs
using Microsoft.AspNetCore.Mvc;
using ProjektBostad.Models;
using Microsoft.AspNetCore.Http;
using static ProjektBostad.Models.Databas;
using System.Net.Mail;
using System.Net;
using static ProjektBostad.Models.BostadsDetalj;
using Microsoft.AspNetCore.Http;
using BCrypt.Net;
using Microsoft.CodeAnalysis.CodeStyle;
using System.Diagnostics.Tracing;

namespace ProjektBostad.Controllers
{
        
    public class HemnetController : Controller
    {

        private readonly IEmailSender _emailSender; 
        public HemnetController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [HttpGet]
        public IActionResult LogIn()
        {
           
            return View("LogIn");
        }

        [HttpPost]
        public IActionResult LogIn(Anvandare anv)
        {
            Databas db = new Databas();
            int i = 0;
            string error = "";
            i = db.LoggaIn(anv, out error);

            ViewBag.antal = i;

            if (i == 1)
            {
                (string hashedLosenord, string salt) = db.GetHashedLosenordAndSaltFromDatabase(anv.Anv_Namn);

                if (hashedLosenord != null && salt != null)
                {
                    bool isValidPassword = BCrypt.Net.BCrypt.Verify(anv.Losenord + salt, hashedLosenord);

                    if (isValidPassword)
                    {
                        HttpContext.Session.SetString("IsLoggedIn", "true");
                        HttpContext.Session.SetString("UserName", anv.Anv_Namn);
                        ViewBag.UserName = anv.Anv_Namn;
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

            ViewBag.Felmeddelande = "Fel användarnamn eller lösenord";
            return View("LogIn");
        }
        public IActionResult KopSida(int Id)
        {
            Databas db = new Databas();
            BostadsDetalj bm = db.GetDetaljer(Id, out string error);
            ViewBag.error = error;
            return View(bm);
        }

        public IActionResult UppdateraResultat()
        {
            return View();
        }
        public IActionResult RaderaResultat()
        {
            return View();
        }
        public IActionResult KontoResultat()
        {
            return View();
        }
        public IActionResult BostadControll()
        {
            List<BostadsDetalj> Bostadslista = new List<BostadsDetalj>(); 
            Databas bm = new Databas();
            string error = "";
            Bostadslista = bm.VisaBostad(out error);
            ViewBag.error = error;
            ViewBag.Antal = HttpContext.Session.GetString("antal"); 
            return View(Bostadslista);
        }
        [HttpGet]
        public IActionResult SkapaAnvandare()
        {
            return View("SkapaAnvandare");
        }
        [HttpPost]
        public IActionResult SkapaAnvandare(Anvandare anv)
        {
            Databas db = new Databas();
            int i = 0;
            string error = "";
            i = db.SkapaAnv(anv, out error);        
            ViewBag.error = error;
            ViewBag.antal = i;
            if (i == 1)
            {
                return RedirectToAction("KontoResultat");
            }
            else
            {
                Console.WriteLine("Det gick inte att skapa ditt konto");
                return View("SkapaAnvandare");
            }
        }
        public IActionResult TaBortAnvandare(Anvandare anv)
        {
            Databas db = new Databas();
            int i = 0;
            string error = "";
            i = db.TaBortAnv(anv, out error);
            HttpContext.Session.SetString("antal", i.ToString());
            if (i == 1)
            {
                
                return RedirectToAction("RaderaResultat");
            }
            else
            {
                Console.WriteLine("Det gick inte att skapa ditt konto");
                return View("TaBortAnvandare");

            }
        }
        public IActionResult UppdateraAnvandare(Anvandare anv)
        {
            Databas db = new Databas();
            int i = 0;
            string error = "";
            i = db.UppdateraAnv(anv, out error);
            HttpContext.Session.SetString("antal", i.ToString());
            if (i == 1)
            {

                return RedirectToAction("UppdateraResultat");
            }
            else
            {
                Console.WriteLine("Det gick inte att skapa ditt konto");
                return View("TaBortAnvandare");

            }
        }
        public IActionResult KopFormular()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> KopFormular(BankModell model)
        {

            Databas db = new Databas();
            int i = 0;
            string error = "";
            i = db.BankUpg(model, out error);
            HttpContext.Session.SetString("antal", i.ToString());
            if (i == 1)
            {
                var subject = "Bekräftelse av köp";
                var message = "Hej, " + model.Fornamn + " Tack för ditt köp. Vi har mottagit din betalning";
                var resultat = "Tack för ditt köp, Vi har skickat ett konfirmationsmail till: " + model.Email + "";
                await _emailSender.SendEmailAsync(model.Email, subject, message);

                ViewBag.Email = resultat;

                return View("Confirmation", model);
             
            }
            else
            {
                Console.WriteLine("Det gick inte regristrera bankuppgifter");
                return View("KopFormular");

            }

           
        }
        public IActionResult Confirmation()
        {
            return View();
        }

      

    }
}

Views/Hemnet/BostadControll.cshtml
@model IEnumerable<ProjektBostad.Models.BostadsDetalj>


<style> 


    h1{
        color: white;
        font-family: Rage;
        text-align:center;
       align-items: center;
    }
    body{
        background-color: darkslateblue;
    }

    .full-height{
        height: 100vh;
        width:contain;
    }

    .container{
        width:contain;

    }
    
    .h1{
        text-align: center;
        font-family: Algerian;


    }
    .card {
        border: 1px solid #ccc;
        border-radius: 10px;
        padding: 10px;
        transition: transform 0.2s;
        background-size: contain;
        background-repeat: no-repeat;
      
    }

        .card:hover {
            transform: scale(1.05);
        }

    .card-title {
        font-size: 1.25rem;
        font-weight: bold;
        margin-bottom: 0.5rem;
    }

    .card-text {
        font-size: 0.9rem;
        color: black;
        
        border: 10px;
        border-color: black;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }


</style>
<div class="container full-height">
    <h1>Bostäder till salu</h1>

    @if (Model != null)
    {
        
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 mb-4">
                    <div class="card" style="background-image: url('@item.Bild');">
                        <div class="card-body">
                            <h5 class="card-title">@item.Bostadsnamn</h5>
                            <p class="card-text">@item.Adress, @item.Postkod @item.Stad </p>
                            <p class="card-text">Kostnad: @item.Kostnad kr</p>         
                            <p class="card-text">Kvm: @item.Kvm</p>                           
                            <a asp-action="KopSida" asp-route-id="@item.Anlagg_Id" class="btn btn-primary" target="_blank">Köp nu</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <p>Finns ingen data</p>
    }

    @if (ViewBag.antal != "")
    {
        
        <p>ViewBag.antal innehåller: @ViewBag.antal</p>
    }
    @if (ViewBag.error != "")
    {
        <p>ViewBag.antal innehåller: @ViewBag.error</p>
    }
</div>

Views/Hemnet/Confirmation.cshtml
@model ProjektBostad.Models.BankModell

<h2>Confirmation</h2>

<p>Email: @ViewBag.Email</p>

Views/Hemnet/KontoResultat.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style> 

    h1{
        align-content: center;
        align-items: center;

    }
</style>

<h1> Grattis, och välkommen. Ditt konto har skapats!</h1>
<p> Klicka <a href="@Url.Action("LogIn", "Hemnet")">här</a> för att logga in.</p>


Views/Hemnet/KopFormular.cshtml
@model ProjektBostad.Models.BankModell

@{
    ViewData["Title"] = "KopFormular";
}

<style>

     body{
        background-image: url('/Bilder/bla.webp');
        background-size: cover;
        background-position: center;
     }
    .container {
        max-width: 600px;
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 8px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .form-group label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px; 
    }
    .form-control {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        border: 1px solid #ccc;
        border-radius: 4px;
        margin-bottom: 10px; 
    }
    .btn-primary {
        background-color: #007bff;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        color: #fff;
        font-size: 16px;
        cursor: pointer;
        margin-top: 10px; /* Add some space above the button */
    }

   .btn-primary:hover {
            background-color: #0056b3;
   }
    .kontonummer-input {
        position: relative;
    }

        .kontonummer-input input {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .kontonummer-input::before {
            content: "-";
            position: absolute;
            right: 100%;
            top: 50%;
            transform: translateY(-50%);
            padding: 10px;
            color: #555;
        }


</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 >Betalningsinformation</h2>
            
            <hr />

            <form asp-action="KopFormular">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Fornamn" class="control-label" required>Förnamn</label>
                    <input asp-for="Fornamn" class="form-control" />
                    <span asp-validation-for="Fornamn" class="text-danger">*</span>
                </div>

                <div class="form-group">
                    <label asp-for="Efternamn" class="control-label" required></label>
                    <input asp-for="Efternamn" class="form-control" />
                    <span asp-validation-for="Efternamn" class="text-danger">*</span>
                </div>

                <div class="form-group">
                    <label asp-for="Email" class="control-label" required></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger">*</span>
                </div>

                <div class="form-group">
                    <label asp-for="Kontonummer" class="control-label" required></label>
                    <div class="kontonummer-input">
                        <input asp-for="Kontonummer" class="form-control" />
                    </div>
                    <span asp-validation-for="Kontonummer" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Fakturering" class="control-label" required >Faktureringsadress</label>
                    <input asp-for="Fakturering" class="form-control" />
                    <span asp-validation-for="Fakturering" class="text-danger">*</span>
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Bekräfta Köp" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Hemnet/KopSida.cshtml

@model ProjektBostad.Models.BostadsDetalj
<meta name="keywords" content="Bostad, hitta boende, köpa hus, billig bostad, hitta hem, köpa hem, mäklare" />
<meta name="description" content="ProjektBostad är en webbsida som publicerar bostäder över hela landet till ett billigt pris" />
<meta name="og:url" content="https://localhost:7287/Hemnet/KopSida/@Html.DisplayFor(model=> model.Anlagg_Id)" />
<meta title="ProjektBostad" />
<meta property="og:title" content="@Html.DisplayFor(model=> model.Bostadsnamn)" />
<meta property="og:type" content="@Html.DisplayFor(model=> model.Typ_Id)" />
<meta property="og:image" content="@Html.DisplayFor(model=> model.Bild)" />

@{
    ViewData["Title"] = "KopSida";
}


<style>
    body {
        background-color: darkslateblue;
       
    }
    .property-details {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        text-align: center;
    }

        .property-details h1 {
            font-size: 36px;
            margin-bottom: 10px;
            color: #333;
        }

        .property-details h4 {
            font-size: 24px;
            margin-bottom: 20px;
            color: #555;
        }

        .property-details hr {
            border: 1px solid #ccc;
            margin-bottom: 20px;
        }

        .property-details dl {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            
        }

        .property-details dt, .property-details dd {
            width: 48%;
            margin-bottom: 10px;
            text-align: left;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
        }

        .property-details dt {
            font-weight: bold;
            font-size: 18px;
        }
        .img{
            background-image: url('@Model.Bild');
            background-size: 400px;    
        
        }

        .property-details dd {
            font-size: 18px;
        }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        border-radius: 5px;
        cursor: pointer;
        color: #fff;
        background-color: #007bff;
        border: none;
        transition: background-color 0.3s;
    }

        .button:hover {
            background-color: #0056b3;
        }


    .button1{
        display: inline-block;
        padding: 10px 20px;
        font-size: 18px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        border-radius: 5px;
        cursor: pointer;
        color: #fff;
        background-color: lightblue;
        border: none;
        transition: background-color 0.3s;
    }

</style>



<div class="btn">
    <a asp-action="BostadControll" class="button1">Tillbaka</a>
</div>
<div class="property-details">
    <h1>@Model.Bostadsnamn</h1>
    @ViewBag.error
    

   
    <dl class="row">
        
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Kostnad)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Kostnad)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Kvm)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Kvm)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Adress)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Adress)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Bostadsnamn)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Bostadsnamn)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Postkod)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Postkod)</dd>

        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Stad)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Stad)</dd>
        
    </dl>

    <div class="img">
        <img src="@Model.Bild" alt="@Model.Bostadsnamn" style="max-width: 100%; height: auto;">
    </div>
    <div class="btn">
        <a asp-action="KopFormular" class="button">Köp Bostad</a>
    </div>

 

   


Views/Hemnet/LogIn.cshtml
@model  ProjektBostad.Models.Anvandare


<style>

    body {
        background-image: url('/Bilder/cool.jpg');
        background-size: cover;
        background-position: center;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }
    

    .login-container {
        background-color: white;
        text-align: center;
        max-width: 400px;
        width: 100%;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        margin-left: 365px;
    }

        .login-container input {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
        }

        .login-container button {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

            .login-container button:hover {
                background-color: #0056b3;
            }
</style>



<div class="login-container">
    <form asp-action="LogIn" asp-controller="Hemnet" class="login-form" method="post">
        <div>
            <label asp-for="Anv_Namn">Användarnamn</label>
            <input asp-for="Anv_Namn" class="form-control" placeholder="Användarnamn" required>
        </div>
        <div>
            <label asp-for="Losenord">Lösenord</label>
            <input asp-for="Losenord" class="form-control" type="password" placeholder="Lösenord" required>
        </div>
        <div>
            <button type="submit" >Logga in</button>
        </div>
    </form>

    <div id="felmeddelande" style="color: blue;">
        @if (!string.IsNullOrEmpty(ViewBag.Felmeddelande))
        {
            @ViewBag.Felmeddelande
        }
    </div>
    <div>
        <a href="@Url.Action("SkapaAnvandare", "Hemnet")">Skapa konto</a>
    </div>
   
</div>

    

 

Views/Hemnet/RaderaResultat.cshtml

@{
    ViewData["Title"] = "RaderaResultat";
}

<h1>Ditt konto har raderats</h1>


Views/Hemnet/SkapaAnvandare.cshtml

@model ProjektBostad.Models.Anvandare

@{
    ViewData["Title"] = "Skapa Användare";
}

<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
        background-image: url('/Bilder/cool.jpg');
        background-size: cover;
        background-position: center;
    }

    .login-form {
        max-width: 300px;
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-control {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .btn-primary {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        color: #fff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    .login-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }
</style>

<div class="login-container">
    <form asp-action="SkapaAnvandare" class="login-form">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Anv_Namn" class="form-control" placeholder="Användarnamn" />
            <span asp-validation-for="Anv_Namn" class="text-danger">*</span>
        </div>
        <div class="form-group">
            <input asp-for="Email" class="form-control" placeholder="E-postadress" />
            <span asp-validation-for="Email" class="text-danger">*</span>
        </div>
        <div class="form-group">
            <input asp-for="Losenord" class="form-control" type="password" placeholder="Lösenord" />
            <span asp-validation-for="Losenord" class="text-danger">*</span>
        </div>
        <div class="form-group">
            <input type="submit" value="Skapa Konto" class="btn btn-primary" />
        </div>
        <div class="form-group">
            <a href="@Url.Action("LogIn", "Hemnet")">Tillbaka</a>
        </div>
    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Hemnet/TaBortAnvandare.cshtml


@model ProjektBostad.Models.Anvandare

@{
    ViewData["Title"] = "Hantera Konto";
}

<style>
    body {
        background-image: url('/Bilder/bla.webp');
        background-size: cover;
        background-position: center;
        justify-content: center;
    }

    .login-form {
        max-width: 300px;
        margin: auto;
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-control {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .btn-primary {
        width: 100%;
        padding: 10px;
        background-color: #007bff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        color: #fff;
    }

    .btn-primay {
        width: 100%;
        padding: 10px;
        background-color: red;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        color: #fff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

.logout{
        width: 300px;
        margin: auto;
        padding: 10px 20px 20px;
        margin-left: -160px;
}
</style>

<h1>Hantera Konto</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="TaBortAnvandare" class="login-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Anv_Namn" class="control-label">Användarnamn</label>
                <input asp-for="Anv_Namn" class="form-control" />
                <span asp-validation-for="Anv_Namn" class="text-danger">* </span>
            </div>

            <div class="form-group">
                <label asp-for="Losenord" class="control-label"> Lösenord</label>
                <input asp-for="Losenord" class="form-control" type="password" placeholder="Lösenord" />
                <span asp-validation-for="Losenord" class="text-danger">* </span>
            </div>

            <div class="form-group">
                <input type="submit" value="Radera Konto" class="btn btn-danger" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <form asp-action="UppdateraAnvandare" class="login-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Anv_Namn" class="control-label" >Användarnamn</label>
                <input asp-for="Anv_Namn" class="form-control" />
                <span asp-validation-for="Anv_Namn" class="text-danger">*</span>
            </div>

            <div class="form-group">
                <label asp-for="Losenord" class="control-label">Nytt lösenord</label>
                <input asp-for="Losenord" class="form-control" type="password" placeholder="Nytt Lösenord" />
                <span asp-validation-for="Losenord" class="text-danger"> * </span>
            </div>

            <input type="hidden" asp-for="Losenord" />

            <div class="form-group">
                <input type="submit" value="Uppdatera Konto" class="btn btn-primary" />
            </div>
        </form>
        <div class="col-md-4">
            <form asp-action="LogIn" class="logout">
                <div class="form-group">
                    <input type="submit" value="Logga ut" class="btn btn-primay"/>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Hemnet/UppdateraResultat.cshtml

@{
    ViewData["Title"] = "UppdateraResultat";
}

<h1>Ditt Konto har uppdaterats</h1>
